" ~/.vimrc: Personal .vimrc file for Vi-Improved.
"
" AUTHOR     Snakevil Zen <zsnakevil@gmail.com>
" COPYRIGHT  © 2011 Snakevil.in.

" {{{ Vim - BEHAVIOR
set nocompatible

" About files encodings.
set fileencodings=utf-8,gbk,default,latin1
set nobomb

" About files formats.
set fileformats=unix,dos,mac

" Enables 'modelines' in each file.
set modeline
set modelines=3

" About folding.
set foldenable
set foldmethod=marker

" About visibile zone.
set scrolloff=5

" About across lines.
set backspace=eol,indent,start
set whichwrap=b,s,<,>,[,]

" About TAB.
set tabstop=4
set softtabstop=4
set expandtab

" About indenting.
set shiftwidth=4
set smarttab
set autoindent
set smartindent

" About searching.
set incsearch
set ignorecase

" About brackets matching.
set showmatch

" About wrapping in multibytes chars.
set formatoptions=Bcmnrt
" }}}

" {{{ Vim - LAYOUT
set textwidth=80
set nowrap

set number
set numberwidth=3

set laststatus=2
set statusline=\ %F\ %r%m%w%=0x%02B\ [%l/%L(%p%%),%c%V]\ %y[%{&ff}]

set ruler
" }}}

" {{{ Vim - HIGHLIGHT
syntax on

colorscheme desert

set lazyredraw

set hlsearch
" }}}

" {{{ Vim - KEYS
" C-A to the beginning in command-line just like Bash.
cnoremap <C-A> <Home>
" C-E to the end in command-line just like Bash.
cnoremap <C-E> <End>
" C-K to erase all of the input contents in command-line just like Bash.
cnoremap <C-K> <C-U>
" }}}

" {{{ Extended - VIMFILES
set runtimepath+=~/.local/ProfileX/share/vim,~/.profilexrc/vim
" }}}

" {{{ Extended - BEHAVIOR
" Removes trailing spaces on saving.
autocmd BufWritePre * sil %s/\s\+$//ge

" Reloads '.vimrc' automatically after modifications.
autocmd! BufWritePost ~/.vimrc source %
" }}}

"vim:ft=vim:fenc=utf-8:ff=unix:ts=4:sts=4:et:ai:si:so=5:fen:fdm=marker
"vim:tw=80:nowrap:nu:nuw=4:sw=4
