#!/bin/bash
#
# http://dev.snakevil.in/profilex/sbin/install
#
# AUTHOR     Snakevil Zen <zsnakevil@gmail.com>
# COPYRIGHT  (c) 2010 Snakevil.be/HERE

PATH_Orig=$PWD

PATH_Inst=`dirname "$0"`
PATH_Inst="${PATH_Orig}/${PATH_Inst}/../src"

[ -d "${PATH_Inst}" ] \
  && [ -f "${PATH_Inst}/bash_profile" ] \
  && [ -f "${PATH_Inst}/bashrc" ] \
  && [ -f "${PATH_Inst}/profile" ] \
  && [ -d "${PATH_Inst}/profilex" ] \
  || {
    echo "Profilex install: Structure broken." >&2
    exit 1
  }

cd "${PATH_Inst}"
PATH_Inst=$PWD

[ -f "${HOME}/.bash_profile" ] \
  && mv -f "${HOME}/.bash_profile" "${HOME}/.bash_profile-backup-by-profilex"
ln -s "${PATH_Inst}/bash_profile" "${HOME}/.bash_profile"

[ -f "${HOME}/.bashrc" ] \
  && mv -f "${HOME}/.bashrc" "${HOME}/.bashrc-backup-by-profilex"
ln -s "${PATH_Inst}/bashrc" "${HOME}/.bashrc"

[ -f "${HOME}/.profile" ] \
  && mv -f "${HOME}/.profile" "${HOME}/.profile-backup-by-profilex"
ln -s "${PATH_Inst}/profile" "${HOME}/.profile"

[ -d "${HOME}/.profilex" ] \
  && rm -fR "${HOME}/.profilex"
ln -s "${PATH_Inst}/profilex" "${HOME}/.profilex"

cd "${PATH_Orig}"

echo "Profilex install: SUCCEED!"
exit

# vim:ft=sh:fenc=utf-8:ff=unix:nowrap:nu:nuw=4
# vim:tw=75:ts=2:sts=2:et:si:ai:sw=2
