# ~/.bash_profile
#
# AUTHOR     Snakevil Zen <zsnakevil@gmail.com>
# COPYRIGHT  © 2011 Snakevil.in.

[ -z "${BASH}" ] && return

SNAKEVIL_SHTYPE="bash"
export SNAKEVIL_SHTYPE

[ -f "${HOME}/.profile" ] && source "${HOME}/.profile"

# vim:ft=sh:fenc=utf-8:ff=unix:tw=75:ts=2:sts=2:et:ai:si
# vim:nowrap:sw=2:nu:nuw=4:so=5:fen:fdm=marker
